# Lychee configuration for Ray.Di documentation link checking
# This configuration is shared across multiple GitHub Actions workflows

# Maximum number of concurrent network requests
max_concurrency = 10

# Request timeout in seconds
timeout = 30

# Number of retries for failed requests
max_redirects = 10

# User agent string
user_agent = "Ray.Di Documentation Link Checker / GitHub Actions"

# Headers to include in requests
headers = [
  "accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "accept-language=en-US,en;q=0.9,ja;q=0.8",
  "cache-control=no-cache"
]

# Exclude patterns
exclude = [
  # Skip localhost and development URLs
  "http://localhost*",
  "https://localhost*",
  "http://127.0.0.1*",
  "https://127.0.0.1*",
  "http://0.0.0.0*",
  "https://0.0.0.0*",
  
  # Skip example URLs
  "http://example.com*",
  "https://example.com*",
  "http://example.org*",
  "https://example.org*",
  
  # Skip file:// URLs
  "file://*",
  
  # Skip mailto links
  "mailto:*",
  
  # Skip social media that might have bot protection
  "https://twitter.com*",
  "https://x.com*",
  "https://instagram.com*",
  "https://facebook.com*",
  
  # Skip LinkedIn (often blocks bots)
  "https://linkedin.com*",
  "https://www.linkedin.com*",
  
  # Skip domains that commonly block automated requests
  "https://medium.com*",
  
  # Skip placeholder/template URLs
  "https://your-domain.com*",
  "http://your-domain.com*"
]

# Include patterns (if specified, only these will be checked)
include = []

# Accept certain HTTP status codes as valid
accept = [200, 201, 202, 204, 206, 300, 301, 302, 303, 304, 307, 308, 429]

# Check links in these file types
include_verbatim = true

# Output format
format = "detailed"

# Check local files
include_local = true